### ISSUE TITLE
Error en la dependencia de Java

### ISSUE THREAD

**Issue by estebanjrdev** [Z17-CU/apklischeckpayment#3]
No me funciona cuando agrego la dependencia para java 

   implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:$LAST_VERSION'

me genera un error

**Comment by cz9dev** [comment]
Puedes mostrar el error?

**Comment by estebanjrdev** [comment]
Me da error ninme deja importar  la dependencia 
![Screenshot_20220605-104245](https://user-images.githubusercontent.com/106480242/172056110-806b8722-7f06-4137-b5d7-6a3bf01b7b67.jpg)

**Comment by cz9dev** [comment]
Mira si el dev no te sugiere nada en este ejemplo utilice si mal no recuerdo está librería. Mírala y compara las diferencias https://github.com/cz9dev/learnApklisJava

**Comment by richardanca** [comment]
> 

Buenos días, donde dice "$LAST_VERSION" debes poner la versión de la librería, quedaría de ésta forma:

implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21'

Saludos 😉

**Comment by cz9dev** [comment]
> > 
> 
> Buenos días, donde dice "$LAST_VERSION" debes poner la versión de la librería, quedaría de ésta forma:
> 
> implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21'
> 
> Saludos 😉
> 

Podrías también declarar anteriormente una variable LAST_VERSION con la versión a utilizar.

**Comment by estebanjrdev** [comment]
Ya me funciono  así
implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21'

**Comment by estebanjrdev** [comment]
Gracias

**Comment by cz9dev** [comment]
Bueno ya puede cerrar el hilo el dev. Saludos

**Comment by estebanjrdev** [comment]
Ahora me esta dando otro problema 
![Screenshot_20220610-085841](https://user-images.githubusercontent.com/106480242/173069978-5d725d8e-9e92-4d50-8acc-50c827d1c6f9.jpg)
No me deja importar la clase Verify

**Comment by richardanca** [comment]
Importaste la librería?

implementation 'com.github.Z17-CU:apklischeckpayment:0.0.2'

**Comment by estebanjrdev** [comment]
Importe está 
	implementation 'org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.6.21'
que es la que dice que se debe usar para aplicaciones java
![Screenshot_20220610-110300](https://user-images.githubusercontent.com/106480242/173094792-9fb10e54-00ef-4578-bfaf-e82ba41ee584.jpg)

**Comment by richardanca** [comment]
Esa q ya importaste mantenla y añde esta otra:

implementation 'com.github.Z17-CU:apklischeckpayment:0.0.2'

**Comment by estebanjrdev** [comment]
Si ya probé y me genera un error

**Comment by estebanjrdev** [comment]
![Screenshot_20220610-120350](https://user-images.githubusercontent.com/106480242/173107604-20e1a7b8-db6d-4e64-9596-2d49b187f5e2.jpg)

**Comment by estebanjrdev** [comment]
Problema resuelto
